### ISSUE TITLE
webpack-dev-server not found on compose up 

### ISSUE THREAD

**Issue by joshchernoff** [bikeindex/bike_index#1846]
After bumping the ruby version to 2.7 and building and running `./bin/setup` I'm now seeing a failure when trying to boot locally. 

```
docker-compose up
[...]
app_1       | 20:13:36 webpacker.1   | yarn run v1.22.5
app_1       | 20:13:36 webpacker.1   | error Command "webpack-dev-server" not found.
app_1       | 20:13:36 webpacker.1   | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
app_1       | 20:13:37 webpacker.1   | exited with code 1
```

**Comment by sethherr** [comment]
I'm 60% confident that this was because the line in the Procfile didn't include `bundle exec`, which will be fixed in #1847

**Comment by sethherr** [comment]
@joshchernoff - would you try pulling the most recent from `main` and trying again?

**Comment by joshchernoff** [comment]
Yeah seen your fix, prob the bundle exec as shown. Will close out if fixed.

**Comment by joshchernoff** [comment]
Still seeing it, https://gist.github.com/joshchernoff/b1fa61f008fb58f56253ad4e4f4f52a4

**Comment by joshchernoff** [comment]
Also seeing a bunch of 
```
'ErbParser' is ignored.
'RubyParser' is ignored.
```

This lead me to https://gitmemory.com/issue/ruby-gettext/gettext/64/569920320
Though probably a side issue related to ripper or something that's using the IRB parser

**Comment by sethherr** [comment]
Try running `docker-compose run app yarn install`

**Comment by sethherr** [comment]
A few other minor things caused me some problems - after getting the most up to date version of `main` (I just merged PR #1848), remove `node_modules` and then run the install again.

I now have the docker container running successfully locally, so I _think_ it should work for you @joshchernoff 

... but I don't have an answer to the `'ErbParser' is ignored` issue right now.

**Comment by joshchernoff** [comment]
I've tried in the order of 
* `docker-compose run app rm -rf node_moduels`
* `docker-compose build --no-cache app
* `docker-compose run app ./bin/setup`
* `docker-compose up`

And I still see 
```
app_1       | 19:37:09 webpacker.1   | yarn run v1.22.5
app_1       | 19:37:10 webpacker.1   | error Command "webpack-dev-server" not found.
app_1       | 19:37:10 webpacker.1   | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
app_1       | 19:37:10 webpacker.1   | exited with code 1
app_1       | 19:37:10 system        | sending SIGTERM to all processes
```

**Comment by joshchernoff** [comment]
After a second try, it looked like I needed to run `yarn install`
Noticed 
```
  # Install JavaScript dependencies if using Yarn
  # system('bin/yarn')
```
was commented out in setup. 

After waiting forever for `Linking dependencies...` to finish it looks like it worked.

**Comment by sethherr** [comment]
Thanks for figuring out _why_ yarn wasn't installing!

**Comment by joshchernoff** [comment]
Thanks for helping me get this stood up locally. I hope to get in a few hours here and there soon :)
