### ISSUE TITLE
Upload photo failures in Production

### ISSUE THREAD

**Issue by FlipEnergy** [bikeindex/bike_index#2534]
I'm trying to upload pictures of my bike an keep running into this error:
```
Failed to upload public_image: #{j @public_image.errors.full_messages.join(', ').html_safe} 
```
![image](https://github.com/bikeindex/bike_index/assets/7714381/ba7053fc-033a-4ff7-a747-ccbc837c2aab)

Tried using the following browsers:
- Firefox: 124.0.1 (64-bit)
- Google Chrome: Version 122.0.6261.128 (Official Build) (64-bit)

**Comment by sethherr** [comment]
Oh damn, that's frustrating.

I think the issue is connected to a problem with one of our servers - I plan to upgrade them in the next few days. 

I'll let you know when I do and check in to see if it solves it.

**Comment by sethherr** [comment]
Hey @FlipEnergy - this should be solved now. Please give it a try and let me know if you're still running into problems!

**Comment by FlipEnergy** [comment]
> Hey @FlipEnergy - this should be solved now. Please give it a try and let me know if you're still running into problems!

Nope, still getting the same error uploading to https://bikeindex.org.

**Comment by lzlrd** [comment]
Can confirm I'm also experiencing the same error. Was able to upload a screenshot of a receipt, however.

**Comment by sethherr** [comment]
Pretty sure this is actually fixed now!

Sorry for the loooooong delay
